Add domain support for confidentials
aleph-im/front-aleph-cloud-page pull request #102
Opened 2024-08-27 22:00 UTC by philogicae

This is a draft, I just wanted to test some stuff and I ended up doing few fixes/improvements:

- Continued confidential current implementation
- Fixed /settings/domain/[domain]
- Updated /settings/domain/new for confidential support
- Display right entity type

2024-08-28 07:30 UTC, hoh commented
Is this still a draft as described in the body of the PR ?

2024-08-28 08:50 UTC, philogicae commented
> Is this still a draft as described in the body of the PR ?

1) Since the coco instance implementation on front isn't done yet, @amalcaraz / @gmolki have to check if my changes here are fine

2) I still have to check with @aliel why DNS resolution is currently not working for coco domains, despite the changes

2024-09-10 09:45 UTC, amalcaraz requested changes
LGTM, minor change requested tho

2024-09-10 09:45 UTC, amalcaraz commented on src/components/pages/dashboard/ManageDomain/cmp.tsx
> +  const is_confidential = domain.target == EntityDomainType.Confidential
in javascript by convention variables are camelCase, please replace it everywhere it has been set in snake_case

2024-09-27 14:18 UTC, merged